### ISSUE TITLE
please include license to this project

### ISSUE THREAD

**Issue by aksharlabs** [brihat-rb/brihat_calendar#1]
there is not license provided on project and files please add license.

**Comment by aksharlabs** [comment]
please include copyright on every file like this and put licence file on main project
/* Copyright (C) 2022 brihat bajracharya(brihatbajracharya@gmail.com) - All Rights Reserved
 * You may use, distribute and modify this code under the
 * terms of the ...... license
 *  * You should have received a copy of the ....... license with
 * this file. If not, please write to: , or visit :.........
 */

**Comment by brihat-rb** [comment]
Add License and Copyright Notice
